### ISSUE TITLE
save embedding failed: ' {"message":"Request failed with status code 429"}.

### ISSUE THREAD

**Issue by github-swl** [guangzhengli/ChatFiles#115]
Hi, I've had this error when I run locally. I uploaded the file in `doc/example/beiying.txt` successfully while the error message occurs with beginning embedding handler.

```
beginning embedding handler
Error: Request failed with status code 429
    at createError (/Users/research/ChatFiles/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/research/ChatFiles/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/research/ChatFiles/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1378:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Thanks in advanced.

<img width="552" alt="截圖 2023-07-27 下午5 38 23" src="https://github.com/guangzhengli/ChatFiles/assets/140705087/27321d9e-1e68-45b2-8b15-e0abafb5cce5">

**Comment by guangzhengli** [comment]
The HTTP 429 is Too Many Requests response status code indicates the user has sent too many requests in a given amount of time, Can you restart your service and retry upload?

**Comment by github-swl** [comment]
Sorry, I found the reason is that the free trial usage is expired. When I set up payment method, it can work. Thank you.
