### ISSUE TITLE
部署chatfiles-ui，执行"npm run dev"报下面的错误，请教怎么解决。谢谢啦！

### ISSUE THREAD

**Issue by zhangzhanhui** [guangzhengli/ChatFiles#76]
root@HPSTAR14:~/ChatFiles/chatfiles-ui# npm run dev

> chatfiles-ui@0.1.0 dev
> next dev

/root/ChatFiles/chatfiles-ui/node_modules/next/dist/cli/next-dev.js:362
            showAll: args["--show-all"] ?? false,
                                         ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.dev (/root/ChatFiles/chatfiles-ui/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/root/ChatFiles/chatfiles-ui/node_modules/next/dist/bin/next:141:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code 1
npm ERR! path /root/ChatFiles/chatfiles-ui
npm ERR! command failed
npm ERR! command sh -c next dev

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-06-01T11_18_09_835Z-debug.log

**Comment by qq31682216** [comment]
把node升级到v19版本就可以了

**Comment by guangzhengli** [comment]
Currently, the entire project has been refactored using Langchain and this issue has been resolved. #81
