### ISSUE TITLE
The vercel deployment is successful, but an error occurs when uploading the file: save embedding failed`.

### ISSUE THREAD

**Issue by alistaitsacle** [guangzhengli/ChatFiles#88]
The vercel deployment is successful, but an error occurs when uploading the file: save embedding failed`.

**Comment by guangzhengli** [comment]
Hi. Can you provide more detailed logs found in Vercel logs after you upload the file?

**Comment by chen198328** [comment]
beginning embedding handler
Error: Error inserting: unsupported Unicode escape sequence 400 Bad Request
    at SupabaseVectorStore.addVectors (file:///var/task/node_modules/langchain/dist/vectorstores/supabase.js:52:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async saveEmbeddings (/var/task/.next/server/chunks/248.js:92:9)
    at async handler (/var/task/.next/server/pages/api/embedding.js:112:9)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/var/task/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/var/task/node_modules/next/dist/server/base-server.js:375:20)

**Comment by guangzhengli** [comment]
This may be due to errors caused by characters in the uploaded file that are not supported by langchain or supabase.
